In [0]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Practice 03').getOrCreate()
df = spark.read.option("header", True).csv('/FileStore/tables/StudentData.csv')

# Count() with filter()
df.filter(df.course == 'DB').count()

# distinct() -> SHOW unique data
df.select(df.course).distinct().show()

# dropDuplicates() -> remove duplicates
df.dropDuplicates(['gender','course']).show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|Female| Hubert Oliveras|    DB| 02984|   59|Annika Hoffman_Na...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 28|Female|  Alberta Freund|   OOP|251805|   83|Annika Hoffman_Sh...|
| 29|Female|  Loris Crossett|    PF|201487|   96|Elenore Choy_Lati...|
| 29|  Male|     Billi Clore| Cloud|512047|   76|Taryn Brownlee_Ju...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
+---+------+----------------+------+------+-----+--------------------+

In [0]:
# Use StudentData.csv
# Read this file in DF
# display all the unique rows for ages, gender, course col

In [0]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Quiz').getOrCreate()
df = spark.read.option("header", True).csv('/FileStore/tables/StudentData.csv')
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB| 02984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
# display all the unique rows for ages, gender, course col
df.select(df.age,df.gender,df.course).dropDuplicates().count()

Out[27]: 24

In [0]:
# display all the unique rows for ages, gender, course col
df.dropDuplicates(['age','gender','course']).count()

Out[29]: 24

In [0]:
df.sort(df.marks, df.age).show() # from low to high
# or
df.sort('marks','age').show()
# or
df.sort(df.marks.asc(), df.age.desc()).show()

+---+------+-----------------+------+-------+-----+--------------------+
|age|gender|             name|course|   roll|marks|               email|
+---+------+-----------------+------+-------+-----+--------------------+
| 28|Female|   Maybell Duguay| Cloud| 261439|   20|Nicole Harwood_Ju...|
| 29|  Male|   Jalisa Swenson|   OOP|4751515|   20|Annika Hoffman_Hu...|
| 28|  Male|  Marylee Capasso|   DSA|2081560|   20|Sheryll Towler_Do...|
| 29|Female|  Gonzalo Ferebee|   DSA|5631172|   20|Jeannetta Golden_...|
| 29|  Male|Michelle Ruggiero|    PF|6001585|   20|Paris Hutton_Marg...|
| 29|  Male|     Elenore Choy|    DB|3652057|   20|Jc Andrepont_Gonz...|
| 29|Female|Michelle Ruggiero|    DB|9232210|   20|Donna Yerby_Latia...|
| 29|Female|   Tamera Blakley|   DSA|3911247|   20|Donna Yerby_Bonit...|
| 28|Female|     Jc Andrepont|    PF| 972733|   20|Eda Neathery_Eda ...|
| 28|  Male|      Abram Nagao| Cloud|2652463|   21|Eda Neathery_Anni...|
| 29|  Male|   Tamera Blakley|   OOP|7341268|   21|Anna Santos_Naoma...|
| 29|Female|  Gonzalo Ferebee|   OOP|2262603|   21|Bonita Higuera_Ch...|
| 28|  Male|    Kizzy Brenner| Cloud|4622328|   21|Leontine Phillips...|
| 29|  Male|  Sebrina Maresca| Cloud|5042394|   21|Donna Yerby_Miche...|
| 28|  Male|   Bonita Higuera| Cloud|7671835|   21|Taryn Brownlee_Se...|
| 29|Female|   Nicole Harwood|    PF|8121198|   21|Bonita Higuera_Pr...|
| 29|Female|   Alberta Freund|   OOP|4501424|   21|Toshiko Hillyard_...|
| 28|Female|  Sebrina Maresca|    PF|5742239|   21|Bonita Higuera_Se...|
| 28|  Male|      Billi Clore|    DB|9151306|   21|Latia Vanhoose_Er...|
| 29|  Male|     Paris Hutton|   MVC| 752504|   22|Elenore Choy_Elen...|
+---+------+-----------------+------+-------+-----+--------------------+
only showing top 20 rows

In [0]:
df.orderBy(df.marks,df.age).show()

+---+------+-----------------+------+-------+-----+--------------------+
|age|gender|             name|course|   roll|marks|               email|
+---+------+-----------------+------+-------+-----+--------------------+
| 28|  Male|  Marylee Capasso|   DSA|2081560|   20|Sheryll Towler_Do...|
| 28|Female|   Maybell Duguay| Cloud| 261439|   20|Nicole Harwood_Ju...|
| 28|Female|     Jc Andrepont|    PF| 972733|   20|Eda Neathery_Eda ...|
| 29|Female|   Tamera Blakley|   DSA|3911247|   20|Donna Yerby_Bonit...|
| 29|  Male|   Jalisa Swenson|   OOP|4751515|   20|Annika Hoffman_Hu...|
| 29|Female|  Gonzalo Ferebee|   DSA|5631172|   20|Jeannetta Golden_...|
| 29|  Male|Michelle Ruggiero|    PF|6001585|   20|Paris Hutton_Marg...|
| 29|Female|Michelle Ruggiero|    DB|9232210|   20|Donna Yerby_Latia...|
| 29|  Male|     Elenore Choy|    DB|3652057|   20|Jc Andrepont_Gonz...|
| 28|  Male|      Abram Nagao| Cloud|2652463|   21|Eda Neathery_Anni...|
| 28|  Male|   Bonita Higuera| Cloud|7671835|   21|Taryn Brownlee_Se...|
| 28|Female|  Sebrina Maresca|    PF|5742239|   21|Bonita Higuera_Se...|
| 28|  Male|    Kizzy Brenner| Cloud|4622328|   21|Leontine Phillips...|
| 28|  Male|      Billi Clore|    DB|9151306|   21|Latia Vanhoose_Er...|
| 29|  Male|  Sebrina Maresca| Cloud|5042394|   21|Donna Yerby_Miche...|
| 29|Female|  Gonzalo Ferebee|   OOP|2262603|   21|Bonita Higuera_Ch...|
| 29|  Male|   Tamera Blakley|   OOP|7341268|   21|Anna Santos_Naoma...|
| 29|Female|   Alberta Freund|   OOP|4501424|   21|Toshiko Hillyard_...|
| 29|Female|   Nicole Harwood|    PF|8121198|   21|Bonita Higuera_Pr...|
| 28|Female|     Cheri Kenney| Cloud|2281771|   22|Tamera Blakley_Ab...|
+---+------+-----------------+------+-------+-----+--------------------+
only showing top 20 rows

In [0]:
# OfficeData.csv
# Read this file in DF
# Create a DF Sorted on Bonus in Ascending order and show it.
# Create a DF sorted on age and salary in descending and ascending order respectively and show it.
# Create a DF sorted on age, bonus and salary in descending, ascending order respectively and show it.

In [0]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Quiz').getOrCreate()
office_df = spark.read.options(header=True, InferSchema=True).csv('/FileStore/tables/OfficeData.csv')
office_df.show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
+-------------+----------+-----+------+---+-----+

In [0]:
office_df.sort(office_df.bonus.asc()).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
+-------------+----------+-----+------+---+-----+

In [0]:
office_df.sort(office_df.age.desc(), office_df.salary.asc()).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|      Michael|     Sales|   NY| 86000| 56|20000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|        James|     Sales|   NY| 90000| 34|10000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

In [0]:
office_df.sort(office_df.age.desc(),office_df.bonus.desc(),office_df.salary.asc()).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|      Michael|     Sales|   NY| 86000| 56|20000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|        James|     Sales|   NY| 90000| 34|10000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

In [0]:
df = spark.read.options(header=True, inferSchema=True).csv('/FileStore/tables/StudentData.csv')
df_sum = df.groupBy("gender").sum('marks')
df_count = df.groupBy("course").count()
df_max = df.groupBy("gender").max("marks")
df_min = df.groupBy("gender").min('marks')
df_mean = df.groupBy("gender").mean('marks')
df_avg = df.groupBy('gender').avg('age')
print('SUM')
df_sum.show()
print('COUNT')
df_sum.show()
print('MAX')
df_max.show()
print('MIN')
df_mean.show()
print('MEAN')
df_mean.show()
print('AVG')
df_avg.show()

SUM
+------+----------+
|gender|sum(marks)|
+------+----------+
|Female|     29636|
|  Male|     30461|
+------+----------+

COUNT
+------+----------+
|gender|sum(marks)|
+------+----------+
|Female|     29636|
|  Male|     30461|
+------+----------+

MAX
+------+----------+
|gender|max(marks)|
+------+----------+
|Female|        99|
|  Male|        99|
+------+----------+

MIN
+------+------------------+
|gender|        avg(marks)|
+------+------------------+
|Female|59.153692614770456|
|  Male| 61.04408817635271|
+------+------------------+

MEAN
+------+------------------+
|gender|        avg(marks)|
+------+------------------+
|Female|59.153692614770456|
|  Male| 61.04408817635271|
+------+------------------+

AVG
+------+------------------+
|gender|          avg(age)|
+------+------------------+
|Female|28.489021956087825|
|  Male| 28.52304609218437|
+------+------------------+

In [0]:
# groupBy( ) in multiple columns and aggregation
from pyspark.sql.functions import sum,count,min,max,mean,avg
df = spark.read.options(header=True, inferSchema=True).csv('/FileStore/tables/StudentData.csv')
df = df.groupby('gender').agg(count('name').alias('Total_name'),sum('marks').alias('SUM'),min('marks').alias('MIN'),max('marks').alias('MAX'),\
                             mean('marks').alias('MEAN'),avg('marks').alias('AVG')).show()

+------+----------+-----+---+---+------------------+------------------+
|gender|Total_name|  SUM|MIN|MAX|              MEAN|               AVG|
+------+----------+-----+---+---+------------------+------------------+
|Female|       501|29636| 20| 99|59.153692614770456|59.153692614770456|
|  Male|       499|30461| 20| 99| 61.04408817635271| 61.04408817635271|
+------+----------+-----+---+---+------------------+------------------+

In [0]:
from pyspark.sql.functions import col
df = spark.read.options(header=True, inferSchema=True).csv('/FileStore/tables/StudentData.csv')

# Transformation
df2 = df.filter(df.gender=='Male')
df3 = df2.groupby('course', 'gender').agg(count("*").alias('Total_enroll'))
df3.filter(df3.Total_enroll > 85).show()
# Alternate
df.filter(df.gender=='Male').groupby('course','gender').agg(count('*').alias('Total_enroll')).filter(col('Total_enroll') >85).show() # Use 'col' for "Total_enroll"

+------+------+------------+
|course|gender|Total_enroll|
+------+------+------------+
|   MVC|  Male|          86|
|    PF|  Male|          97|
| Cloud|  Male|          86|
+------+------+------------+

+------+------+------------+
|course|gender|Total_enroll|
+------+------+------------+
|   MVC|  Male|          86|
|    PF|  Male|          97|
| Cloud|  Male|          86|
+------+------+------------+

In [0]:
# For the quiz you will be using StudentData.csv
# read the file in the dataFrame
# display the total number of students enrolled in each course
# display the total number of male and female students enrolled in each course
# display total number of marks achieved by each gender in each course
# display the min, max, and avg marks achieved in each course by each age group

In [0]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Quiz').getOrCreate()
df = spark.read.options(header=True,inferSchema=True).csv('/FileStore/tables/StudentData.csv')
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.groupby('course').agg(count('*').alias('Total_Student')).show()

+------+-------------+
|course|Total_Student|
+------+-------------+
|    PF|          166|
|    DB|          157|
|   MVC|          157|
|   DSA|          176|
| Cloud|          192|
|   OOP|          152|
+------+-------------+

In [0]:
df.groupby('gender','course').agg(count("*").alias('Total_Student')).show()

+------+------+-------------+
|gender|course|Total_Student|
+------+------+-------------+
|Female| Cloud|          106|
|Female|   OOP|           82|
|  Male|    PF|           97|
|  Male|    DB|           82|
|  Male| Cloud|           86|
|  Male|   OOP|           70|
|Female|   DSA|           98|
|Female|    DB|           75|
|  Male|   DSA|           78|
|  Male|   MVC|           86|
|Female|   MVC|           71|
|Female|    PF|           69|
+------+------+-------------+

In [0]:
df.groupby('gender','course').agg(sum('marks').alias('Total_marks')).show()

+------+------+-----------+
|gender|course|Total_marks|
+------+------+-----------+
|Female| Cloud|       6316|
|Female|   OOP|       4682|
|  Male|    PF|       5960|
|  Male|    DB|       5073|
|  Male| Cloud|       5127|
|  Male|   OOP|       4234|
|Female|   DSA|       6124|
|Female|    DB|       4197|
|  Male|   DSA|       4826|
|  Male|   MVC|       5241|
|Female|   MVC|       4344|
|Female|    PF|       3973|
+------+------+-----------+

In [0]:
df.groupby('age','course').agg(min('marks').alias('MIN'), max('marks').alias('MAX'),avg('marks').alias('AVG')).show()

+---+------+---+---+------------------+
|age|course|MIN|MAX|               AVG|
+---+------+---+---+------------------+
| 29|   OOP| 20| 99|59.729729729729726|
| 28|    PF| 20| 98| 63.75949367088607|
| 28|    DB| 21| 98| 58.76829268292683|
| 28|   DSA| 20| 99|  64.6867469879518|
| 29|    DB| 20| 98|59.346666666666664|
| 28| Cloud| 20| 99|             58.08|
| 29|   DSA| 20| 99| 60.01075268817204|
| 28|   MVC| 23| 99| 60.44444444444444|
| 28|   OOP| 23| 99| 57.64102564102564|
| 29|    PF| 20| 99|56.275862068965516|
| 29|   MVC| 22| 99| 61.56470588235294|
| 29| Cloud| 21| 98|             61.25|
+---+------+---+---+------------------+

In [0]:
rdd = df.rdd
rdd.collect()

Out[91]: [Row(age=28, gender='Female', name='Hubert Oliveras', course='DB', roll=2984, marks=59, email='Annika Hoffman_Naoma Fritts@OOP.com'),
 Row(age=29, gender='Female', name='Toshiko Hillyard', course='Cloud', roll=12899, marks=62, email='Margene Moores_Marylee Capasso@DB.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='PF', roll=21267, marks=45, email='Jeannetta Golden_Jenna Montague@DSA.com'),
 Row(age=29, gender='Female', name='Elenore Choy', course='DB', roll=32877, marks=29, email='Billi Clore_Mitzi Seldon@DB.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=41487, marks=41, email='Claude Panos_Judie Chipps@OOP.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='MVC', roll=52771, marks=32, email='Toshiko Hillyard_Clementina Menke@MVC.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='OOP', roll=61973, marks=69, email='Alberta Freund_Elenore Choy@DB.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='Cloud', roll=72409, marks=85, email='Sheryll Towler_Alberta Freund@Cloud.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='MVC', roll=81492, marks=64, email='Nicole Harwood_Claude Panos@MVC.com'),
 Row(age=29, gender='Male', name='Cordie Harnois', course='OOP', roll=92882, marks=51, email='Judie Chipps_Clementina Menke@MVC.com'),
 Row(age=29, gender='Female', name='Kena Wild', course='DSA', roll=102285, marks=35, email='Dustin Feagins_Margene Moores@OOP.com'),
 Row(age=29, gender='Male', name='Ernest Rossbach', course='DB', roll=111449, marks=53, email='Maybell Duguay_Abram Nagao@OOP.com'),
 Row(age=28, gender='Female', name='Latia Vanhoose', course='DB', roll=122502, marks=27, email='Latia Vanhoose_Mitzi Seldon@OOP.com'),
 Row(age=29, gender='Female', name='Latia Vanhoose', course='MVC', roll=132110, marks=55, email='Eda Neathery_Nicole Harwood@Cloud.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=141770, marks=42, email='Margene Moores_Michelle Ruggiero@MVC.com'),
 Row(age=29, gender='Female', name='Latia Vanhoose', course='DB', roll=152159, marks=27, email='Claude Panos_Santa Kerfien@DB.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='MVC', roll=161771, marks=36, email='Mitzi Seldon_Jenna Montague@MVC.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=171660, marks=22, email='Taryn Brownlee_Mitzi Seldon@MVC.com'),
 Row(age=29, gender='Male', name='Santa Kerfien', course='PF', roll=182129, marks=56, email='Judie Chipps_Taryn Brownlee@Cloud.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DB', roll=192537, marks=62, email='Ernest Rossbach_Marylee Capasso@Cloud.com'),
 Row(age=29, gender='Female', name='Loris Crossett', course='PF', roll=201487, marks=96, email='Elenore Choy_Latia Vanhoose@Cloud.com'),
 Row(age=29, gender='Female', name='Niki Klimek', course='PF', roll=211508, marks=23, email='Cordie Harnois_Judie Chipps@PF.com'),
 Row(age=28, gender='Female', name='Kena Wild', course='Cloud', roll=221750, marks=60, email='Mitzi Seldon_Jenna Montague@DSA.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='DSA', roll=232060, marks=58, email='Billi Clore_Abram Nagao@MVC.com'),
 Row(age=29, gender='Female', name='Anna Santos', course='Cloud', roll=242254, marks=68, email='Jc Andrepont_Hubert Oliveras@Cloud.com'),
 Row(age=28, gender='Female', name='Alberta Freund', course='OOP', roll=251805, marks=83, email='Annika Hoffman_Sheryll Towler@MVC.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='Cloud', roll=261439, marks=20, email='Nicole Harwood_Judie Chipps@DB.com'),
 Row(age=29, gender='Female', name='Paris Hutton', course='DSA', roll=271472, marks=99, email='Sheryll Towler_Alberta Freund@DSA.com'),
 Row(age=29, gender='Female', name='Cheri Kenney', course='Cloud', roll=281408, marks=43, email='Annika Hoffman_Melani Engberg@Cloud.com'),
 Row(age=28, gender='Female', name='Dustin Feagins', course='DSA', roll=291984, marks=82, email='Abram Nagao_Kena Wild@Cloud.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='Cloud', roll=302130, marks=59, email='Sheryll Towler_Leontine Phillips@PF.com'),
 Row(age=28, gender='Female', name='Anna Santos', course='DB', roll=311589, marks=79, email='Celeste Lollis_Mickey Cortright@DSA.com'),
 Row(age=28, gender='Female', name='Cheri Kenney', course='MVC', roll=321816, marks=24, email='Kena Wild_Michelle Ruggiero@DB.com'),
 Row(age=28, gender='Female', name='Loris Crossett', course='PF', roll=332739, marks=62, email='Michelle Ruggiero_Clementina Menke@DB.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DSA', roll=342003, marks=44, email='Mitzi Seldon_Jeannetta Golden@PF.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='OOP', roll=351719, marks=63, email='Lawanda Wohlwend_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='PF', roll=361316, marks=62, email='Nicole Harwood_Latia Vanhoose@DB.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=372873, marks=45, email='Ernest Rossbach_Toshiko Hillyard@DB.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=381712, marks=36, email='Paris Hutton_Kena Wild@MVC.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='DB', roll=392218, marks=47, email='Leontine Phillips_Billi Clore@MVC.com'),
 Row(age=28, gender='Female', name='Kizzy Brenner', course='Cloud', roll=402409, marks=27, email='Ernest Rossbach_Gonzalo Ferebee@OOP.com'),
 Row(age=29, gender='Female', name='Anna Santos', course='DSA', roll=411479, marks=42, email='Kena Wild_Mitzi Seldon@DB.com'),
 Row(age=28, gender='Male', name='Elenore Choy', course='PF', roll=422704, marks=66, email='Marylee Capasso_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Female', name='Jalisa Swenson', course='OOP', roll=431352, marks=25, email='Gonzalo Ferebee_Judie Chipps@DB.com'),
 Row(age=29, gender='Female', name='Somer Stoecker', course='Cloud', roll=442028, marks=34, email='Taryn Brownlee_Taryn Brownlee@MVC.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='DSA', roll=452141, marks=29, email='Leontine Phillips_Elenore Choy@Cloud.com'),
 Row(age=28, gender='Male', name='Dustin Feagins', course='PF', roll=461839, marks=51, email='Neda Briski_Elenore Choy@Cloud.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=472550, marks=35, email='Mitzi Seldon_Abram Nagao@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='DB', roll=481229, marks=57, email='Clementina Menke_Paris Hutton@MVC.com'),
 Row(age=29, gender='Female', name='Paris Hutton', course='DSA', roll=492159, marks=60, email='Nicole Harwood_Marylee Capasso@OOP.com'),
 Row(age=29, gender='Female', name='Jenna Montague', course='MVC', roll=502585, marks=43, email='Hubert Oliveras_Jc Andrepont@DSA.com'),
 Row(age=29, gender='Male', name='Billi Clore', course='Cloud', roll=512047, marks=76, email='Taryn Brownlee_Judie Chipps@DSA.com'),
 Row(age=29, gender='Male', name='Toshiko Hillyard', course='OOP', roll=521221, marks=77, email='Hubert Oliveras_Latia Vanhoose@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='PF', roll=531530, marks=53, email='Cheri Kenney_Melani Engberg@OOP.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='OOP', roll=542821, marks=28, email='Hubert Oliveras_Priscila Tavernier@PF.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DB', roll=551389, marks=43, email='Tijuana Kropf_Jenna Montague@DB.com'),
 Row(age=29, gender='Male', name='Celeste Lollis', course='DSA', roll=562065, marks=85, email='Jc Andrepont_Melani Engberg@OOP.com'),
 Row(age=28, gender='Female', name='Tijuana Kropf', course='PF', roll=571047, marks=41, email='Loris Crossett_Sebrina Maresca@PF.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='OOP', roll=581756, marks=52, email='Jeannetta Golden_Loris Crossett@MVC.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='DSA', roll=592061, marks=83, email='Eda Neathery_Jenna Montague@Cloud.com'),
 Row(age=28, gender='Female', name='Leontine Phillips', course='DB', roll=602404, marks=48, email='Neda Briski_Cheri Kenney@PF.com'),
 Row(age=28, gender='Female', name='Somer Stoecker', course='Cloud', roll=612490, marks=82, email='Sebrina Maresca_Gonzalo Ferebee@DSA.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DSA', roll=622981, marks=45, email='Lawanda Wohlwend_Loris Crossett@DSA.com'),
 Row(age=29, gender='Female', name='Judie Chipps', course='Cloud', roll=632793, marks=75, email='Tijuana Kropf_Elenore Choy@PF.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='PF', roll=642594, marks=27, email='Marylee Capasso_Claude Panos@DSA.com'),
 Row(age=29, gender='Male', name='Tamera Blakley', course='MVC', roll=651649, marks=92, email='Latia Vanhoose_Toshiko Hillyard@MVC.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='MVC', roll=661079, marks=89, email='Tijuana Kropf_Mickey Cortright@DB.com'),
 Row(age=29, gender='Male', name='Hubert Oliveras', course='MVC', roll=672451, marks=28, email='Annika Hoffman_Mickey Cortright@DSA.com'),
 Row(age=29, gender='Male', name='Sheryll Towler', course='PF', roll=682533, marks=42, email='Billi Clore_Anna Santos@PF.com'),
 Row(age=28, gender='Female', name='Jenna Montague', course='DSA', roll=691564, marks=26, email='Mitzi Seldon_Sebrina Maresca@Cloud.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='PF', roll=701486, marks=99, email='Clementina Menke_Latia Vanhoose@Cloud.com'),
 Row(age=29, gender='Male', name='Jenna Montague', course='MVC', roll=711153, marks=45, email='Marylee Capasso_Hubert Oliveras@DB.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='Cloud', roll=722193, marks=55, email='Taryn Brownlee_Elenore Choy@DB.com'),
 Row(age=28, gender='Female', name='Celeste Lollis', course='DSA', roll=731879, marks=76, email='Hubert Oliveras_Gonzalo Ferebee@DSA.com'),
 Row(age=29, gender='Male', name='Jeannetta Golden', course='MVC', roll=741875, marks=57, email='Sheryll Towler_Cheri Kenney@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='MVC', roll=752504, marks=22, email='Elenore Choy_Elenore Choy@DB.com'),
 Row(age=29, gender='Female', name='Margene Moores', course='MVC', roll=761843, marks=48, email='Ernest Rossbach_Mickey Cortright@DSA.com'),
 Row(age=28, gender='Female', name='Hubert Oliveras', course='DB', roll=771081, marks=79, email='Kizzy Brenner_Dustin Feagins@MVC.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='PF', roll=781061, marks=75, email='Leontine Phillips_Bonita Higuera@PF.com'),
 Row(age=29, gender='Female', name='Billi Clore', course='OOP', roll=791519, marks=93, email='Elenore Choy_Jalisa Swenson@MVC.com'),
 Row(age=28, gender='Female', name='Billi Clore', course='Cloud', roll=801693, marks=38, email='Niki Klimek_Kizzy Brenner@DB.com'),
 Row(age=29, gender='Female', name='Elenore Choy', course='DB', roll=811824, marks=55, email='Maybell Duguay_Melani Engberg@DB.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=822396, marks=47, email='Leontine Phillips_Gonzalo Ferebee@Cloud.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=831562, marks=59, email='Kena Wild_Gonzalo Ferebee@Cloud.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=842515, marks=68, email='Neda Briski_Hubert Oliveras@OOP.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='Cloud', roll=851620, marks=34, email='Melani Engberg_Sheryll Towler@PF.com'),
 Row(age=29, gender='Female', name='Taryn Brownlee', course='MVC', roll=861849, marks=39, email='Billi Clore_Toshiko Hillyard@MVC.com'),
 Row(age=28, gender='Female', name='Sheryll Towler', course='DSA', roll=871967, marks=64, email='Michelle Ruggiero_Billi Clore@Cloud.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='DB', roll=882200, marks=76, email='Michelle Ruggiero_Jenna Montague@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='DSA', roll=892010, marks=93, email='Anna Santos_Naoma Fritts@DSA.com'),
 Row(age=28, gender='Female', name='Somer Stoecker', course='DSA', roll=901958, marks=64, email='Kizzy Brenner_Jc Andrepont@DB.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='PF', roll=911593, marks=46, email='Gonzalo Ferebee_Mitzi Seldon@PF.com'),
 Row(age=29, gender='Female', name='Sebrina Maresca', course='DB', roll=922210, marks=54, email='Toshiko Hillyard_Santa Kerfien@MVC.com'),
 Row(age=29, gender='Male', name='Naoma Fritts', course='DB', roll=931295, marks=79, email='Hubert Oliveras_Sheryll Towler@DSA.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='MVC', roll=941783, marks=94, email='Paris Hutton_Naoma Fritts@DB.com'),
 Row(age=28, gender='Female', name='Lawanda Wohlwend', course='DSA', roll=951686, marks=60, email='Loris Crossett_Nicole Harwood@DSA.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='MVC', roll=962235, marks=32, email='Jenna Montague_Gonzalo Ferebee@DSA.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='PF', roll=972733, marks=20, email='Eda Neathery_Eda Neathery@MVC.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='PF', roll=982443, marks=94, email='Santa Kerfien_Kizzy Brenner@DB.com'),
 Row(age=28, gender='Female', name='Marylee Capasso', course='OOP', roll=991770, marks=86, email='Margene Moores_Clementina Menke@DB.com'),
 Row(age=28, gender='Male', name='Jenna Montague', course='DSA', roll=1002103, marks=36, email='Melani Engberg_Hubert Oliveras@PF.com'),
 Row(age=29, gender='Female', name='Eda Neathery', course='Cloud', roll=1011971, marks=91, email='Margene Moores_Elenore Choy@MVC.com'),
 Row(age=29, gender='Male', name='Michelle Ruggiero', course='DSA', roll=1022971, marks=99, email='Cordie Harnois_Clementina Menke@OOP.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='DB', roll=1031544, marks=44, email='Dustin Feagins_Somer Stoecker@DB.com'),
 Row(age=29, gender='Female', name='Hubert Oliveras', course='DSA', roll=1041483, marks=28, email='Billi Clore_Santa Kerfien@DSA.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='MVC', roll=1052566, marks=78, email='Naoma Fritts_Margene Moores@DSA.com'),
 Row(age=28, gender='Female', name='Nicole Harwood', course='MVC', roll=1061068, marks=82, email='Santa Kerfien_Hubert Oliveras@MVC.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='PF', roll=1071717, marks=54, email='Celeste Lollis_Leontine Phillips@OOP.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='OOP', roll=1081294, marks=94, email='Kizzy Brenner_Anna Santos@OOP.com'),
 Row(age=29, gender='Male', name='Donna Yerby', course='DSA', roll=1092702, marks=79, email='Marylee Capasso_Alberta Freund@OOP.com'),
 Row(age=29, gender='Female', name='Maybell Duguay', course='MVC', roll=1102536, marks=22, email='Somer Stoecker_Marylee Capasso@OOP.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='PF', roll=1112161, marks=42, email='Nicole Harwood_Niki Klimek@DB.com'),
 Row(age=28, gender='Female', name='Bonita Higuera', course='DSA', roll=1122348, marks=51, email='Somer Stoecker_Jenna Montague@DB.com'),
 Row(age=29, gender='Female', name='Melani Engberg', course='OOP', roll=1132093, marks=76, email='Kena Wild_Neda Briski@Cloud.com'),
 Row(age=29, gender='Female', name='Marylee Capasso', course='OOP', roll=1142653, marks=61, email='Cordie Harnois_Alberta Freund@DSA.com'),
 Row(age=29, gender='Male', name='Nicole Harwood', course='Cloud', roll=1152571, marks=62, email='Latia Vanhoose_Maybell Duguay@PF.com'),
 Row(age=29, gender='Female', name='Dustin Feagins', course='OOP', roll=1161607, marks=37, email='Eda Neathery_Marylee Capasso@MVC.com'),
 Row(age=28, gender='Female', name='Niki Klimek', course='PF', roll=1172784, marks=24, email='Jeannetta Golden_Abram Nagao@MVC.com'),
 Row(age=29, gender='Female', name='Abram Nagao', course='DSA', roll=1181007, marks=57, email='Anna Santos_Anna Santos@DSA.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='PF', roll=1192555, marks=77, email='Marylee Capasso_Celeste Lollis@Cloud.com'),
 Row(age=29, gender='Female', name='Ernest Rossbach', course='MVC', roll=1201427, marks=80, email='Elenore Choy_Jenna Montague@OOP.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='DB', roll=1211495, marks=28, email='Melani Engberg_Jc Andrepont@Cloud.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='DB', roll=1222887, marks=75, email='Hubert Oliveras_Somer Stoecker@Cloud.com'),
 Row(age=28, gender='Female', name='Cordie Harnois', course='OOP', roll=1231943, marks=68, email='Mickey Cortright_Kizzy Brenner@OOP.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='OOP', roll=1242426, marks=71, email='Billi Clore_Loris Crossett@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=1251176, marks=60, email='Santa Kerfien_Tamera Blakley@PF.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='Cloud', roll=1261533, marks=70, email='Dustin Feagins_Nicole Harwood@PF.com'),
 Row(age=28, gender='Female', name='Eda Neathery', course='Cloud', roll=1272870, marks=69, email='Somer Stoecker_Dustin Feagins@DB.com'),
 Row(age=28, gender='Female', name='Toshiko Hillyard', course='DSA', roll=1282835, marks=79, email='Somer Stoecker_Toshiko Hillyard@OOP.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1292279, marks=26, email='Paris Hutton_Eda Neathery@DSA.com'),
 Row(age=29, gender='Female', name='Niki Klimek', course='DB', roll=1301784, marks=24, email='Celeste Lollis_Tamera Blakley@DB.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1312294, marks=94, email='Eda Neathery_Priscila Tavernier@PF.com'),
 Row(age=28, gender='Female', name='Leontine Phillips', course='MVC', roll=1322629, marks=87, email='Judie Chipps_Michelle Ruggiero@Cloud.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=1332072, marks=88, email='Billi Clore_Kizzy Brenner@Cloud.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='OOP', roll=1341574, marks=46, email='Elenore Choy_Mickey Cortright@DB.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='PF', roll=1352348, marks=95, email='Neda Briski_Somer Stoecker@DB.com'),
 Row(age=29, gender='Female', name='Jalisa Swenson', course='DSA', roll=1362151, marks=51, email='Lawanda Wohlwend_Jenna Montague@PF.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='PF', roll=1372552, marks=88, email='Hubert Oliveras_Tijuana Kropf@DSA.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='DSA', roll=1382959, marks=66, email='Michelle Ruggiero_Kena Wild@OOP.com'),
 Row(age=29, gender='Female', name='Hubert Oliveras', course='Cloud', roll=1392791, marks=94, email='Anna Santos_Alberta Freund@Cloud.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1401526, marks=24, email='Jc Andrepont_Cheri Kenney@Cloud.com'),
 Row(age=29, gender='Female', name='Clementina Menke', course='OOP', roll=1412376, marks=65, email='Elenore Choy_Latia Vanhoose@DSA.com'),
 Row(age=29, gender='Female', name='Mickey Cortright', course='Cloud', roll=1421542, marks=71, email='Latia Vanhoose_Kena Wild@OOP.com'),
 Row(age=29, gender='Female', name='Leontine Phillips', course='DB', roll=1432252, marks=67, email='Billi Clore_Sheryll Towler@DB.com'),
 Row(age=28, gender='Female', name='Nicole Harwood', course='PF', roll=1441367, marks=95, email='Jc Andrepont_Anna Santos@DSA.com'),
 Row(age=28, gender='Female', name='Gonzalo Ferebee', course='DB', roll=1451513, marks=69, email='Claude Panos_Tamera Blakley@PF.com'),
 Row(age=29, gender='Female', name='Judie Chipps', course='DB', roll=1461078, marks=31, email='Tijuana Kropf_Billi Clore@OOP.com'),

In [0]:
df = spark.read.option("header", True).csv('/FileStore/tables/StudentData.csv')

df.createOrReplaceTempView("Student")
spark.sql("select name, age, course from Student").show()

+----------------+---+------+
|            name|age|course|
+----------------+---+------+
| Hubert Oliveras| 28|    DB|
|Toshiko Hillyard| 29| Cloud|
|  Celeste Lollis| 28|    PF|
|    Elenore Choy| 29|    DB|
|  Sheryll Towler| 28|   DSA|
|  Margene Moores| 28|   MVC|
|     Neda Briski| 28|   OOP|
|    Claude Panos| 28| Cloud|
|  Celeste Lollis| 28|   MVC|
|  Cordie Harnois| 29|   OOP|
|       Kena Wild| 29|   DSA|
| Ernest Rossbach| 29|    DB|
|  Latia Vanhoose| 28|    DB|
|  Latia Vanhoose| 29|   MVC|
|     Neda Briski| 29|    PF|
|  Latia Vanhoose| 29|    DB|
|  Loris Crossett| 29|   MVC|
|  Annika Hoffman| 29|   OOP|
|   Santa Kerfien| 29|    PF|
|Mickey Cortright| 28|    DB|
+----------------+---+------+
only showing top 20 rows

In [0]:
# there are 4 modes: 1) overwrite
#                    2) append
#                    3) ignore
#                    4) error

df = spark.read.options(header=True,inferSchema=True).csv('/FileStore/tables/StudentData.csv')
df.write.options(header=True).csv('/FileStore/tables/df_output/StudentData.csv')

# Or add with mode()
df.write.mode("overwrite").options(header=True).csv('/FileStore/tables/df_output/StudentData.csv')
# or
df.write.mode("append").options(header=True).csv('/FileStore/tables/df_output/StudentData.csv')
# or
df.write.mode("ignore").options(header=True).csv('/FileStore/tables/df_output/StudentData.csv')